<?php

// autoload_namespaces.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);

return array(
    'VirusTotal' => array($baseDir . '/Src'),
    'Tests\\VirusTotal' => array($baseDir . '/Tests'),
    'Prophecy\\' => array($vendorDir . '/phpspec/prophecy/src'),
);
